### ISSUE TITLE
遇到个奇怪的问题。

### ISSUE THREAD

**Issue by smthemex** [fudan-generative-vision/hallo2#10]
推理的时候，2个向量不匹配，torch.Size([2, 12288, 320]) torch.Size([6, 4096, 320])，过att2的值发生了偏移，这事有遇到过没有？
[link](https://github.com/fudan-generative-vision/hallo2/blob/673f3a55f20190ec40f5ddd1b5c6bfa81cf78a55/hallo/models/attention.py#L379-L379C56)

**Comment by cuijh26** [comment]
请问能描述详细点吗？比如是哪两个向量？推理具体是报了什么错？能否看下log呢？

**Comment by smthemex** [comment]
查了下代码，漏了修改ReferenceAttentionControl的导入，已经解决,感谢回复。
![image](https://github.com/user-attachments/assets/b9a0ec24-87a5-4a79-b013-36cc368df7df)

**Comment by XCLIN00ZZ** [comment]
我也这样了，请问你是怎么解决的呢？
