### ISSUE TITLE
runway sd1.5 broken link

### ISSUE THREAD

**Issue by linuxandchill** [fudan-generative-vision/hallo2#13]
fine-tuned sd in the huggingface url doesn't exist 

```[StableDiffusion V1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5): Initialized and fine-tuned from Stable-Diffusion-v1-2. (Thanks to [runwayml](https://huggingface.co/runwayml))```

**Comment by cuijh26** [comment]
Sorry, I forgot to modify README. runway has deleted their model.  You can dowmload this model from https://huggingface.co/fudan-generative-ai/hallo2/tree/main/stable-diffusion-v1-5.

**Comment by superlbr** [comment]
README still under modify
