### ISSUE TITLE
Invalid Decimal Literal

### ISSUE THREAD

**Issue by BAIS1C** [fudan-generative-vision/hallo2#17]
(hallo) F:\FF\hallo2\configs\inference>python long.yaml
  File "F:\FF\hallo2\configs\inference\long.yaml", line 38
    model_path: ./pretrained_models/wav2vec/wav2vec2-base-960h
                                                            ^
SyntaxError: invalid decimal literal

THE ^ is under the 0 in 960h

I have not amended this wav2vec entry in long.yaml

File directory has been checked it was cloned from hugging face as per 
git lfs install
git clone https://huggingface.co/fudan-generative-ai/hallo2 pretrained_models

**Comment by cuijh26** [comment]
`python long.yaml`
This command is wrong. 
You should run this command: 
`python scripts/inference_long.py --config ./configs/inference/long.yaml`

**Comment by AricGamma** [comment]
Closing this issue. If any further problems, please reopen it.
