### ISSUE TITLE
Training data process

### ISSUE THREAD

**Issue by Xiang-Deng00** [fudan-generative-vision/hallo2#60]
Hello, congradulation for such nice work! 
I'm wondering how do you align the fps for training videos, e.g. 30fps and 25fps.
Thanks very much!

**Comment by cuijh26** [comment]
We change the fps of all traing video to 25 fps using ffmpeg.

**Comment by Xiang-Deng00** [comment]
> We change the fps of all traing video to 25 fps using ffmpeg.

Would change the video's fps using ffmpeg influence the sync between audio and video?

**Comment by cuijh26** [comment]
Maybe not. We sample the origin audio using the 16k sampling rate.  You can see here. (https://github.com/fudan-generative-vision/hallo2/blob/main/hallo/datasets/audio_processor.py#L111)

**Comment by Xiang-Deng00** [comment]
Got it, Thanks for your reply!
