### ISSUE TITLE
请问推理和训练需要多大显存？

### ISSUE THREAD

**Issue by walkingwithGod2017** [fudan-generative-vision/hallo2#8]
弟兄你们好，感谢你们的出色研究工作，这对于数字人生态来说又是一个巨大推动！想问下这个项目，推理和训练大概需要多大显存？感谢回复！

**Comment by cuijh26** [comment]
推理大概12G左右显存，训练我们使用的是8卡a100

**Comment by walkingwithGod2017** [comment]
> 推理大概12G左右显存，训练我们使用的是8卡a100

好的，非常感谢。如果后续有时间，或许可以考虑在Huggingface上出个demo演示，这样能先看下推理效果。感谢你们的研究工作！

**Comment by AricGamma** [comment]
Closing this issue. If any other questions, please open a new one.
